<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="FATEEMA-PC" failures="1" tests="6" name="AmazonSearch" time="0.067" errors="0" timestamp="1 Dec 2019 12:13:55 GMT">
  <testcase classname="in.amazon.testCases.TC003" name="a" time="0.008"/>
  <testcase classname="in.amazon.testCases.TC004" name="a" time="0.015"/>
  <testcase classname="in.amazon.testCases.TC003" name="f" time="0.003"/>
  <testcase classname="in.amazon.testCases.TC004" name="b" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
	at in.amazon.testCases.TC004.b(TC004.java:18)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- b -->
  <testcase classname="in.amazon.testCases.TC004" name="c" time="0.005"/>
  <testcase classname="in.amazon.testCases.TC004" name="d" time="0.001"/>
</testsuite> <!-- AmazonSearch -->
